import {Component} from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {

  headers: any = {
    thead: ['dID', 'NAME', 'ADDRESS', 'REF'],
    displayed: ['id', 'supplierName', 'supplierAddress', 'supplierReference']
  };

  dataSource: any =
    [{
      'id': 20,
      'supplierName': 'asdfasdf',
      'supplierAddress': 'asdf',
      'supplierReference': 'asdfasdfasfasdfa',
      'supplierContact': '2342423423',
      'supplierBankDetails': 'asdf',
      'supplierCustomAttrib1': 'asfasdfasfa',
      'supplierCustomAttrib2': 'true',
      'supplierCustomAttrib3': '0%',
      'supplierCustomAttrib4': 'yes',
      'supplierCustomAttrib5': 'asdfasdf',
      'createdBy': null,
      'createdDate': '05-12-2018 10:42:05',
      'modifyBy': null,
      'modifyDate': null
    },
      {
        'id': 21,
        'supplierName': 'asdfasdf',
        'supplierAddress': 'asdfsdfasdfasdf',
        'supplierReference': 'asdfasdfasfasdfa',
        'supplierContact': '2342423423',
        'supplierBankDetails': 'asdf',
        'supplierCustomAttrib1': 'asfasdfasfa',
        'supplierCustomAttrib2': 'true',
        'supplierCustomAttrib3': '0%',
        'supplierCustomAttrib4': 'no',
        'supplierCustomAttrib5': 'asdfasdf',
        'createdBy': null,
        'createdDate': '05-12-2018 14:02:07',
        'modifyBy': null,
        'modifyDate': null
      },
      {
        'id': 22,
        'supplierName': 'asdfasdf',
        'supplierAddress': 'asdfsdfasdfasdf',
        'supplierReference': 'asdfasdfasfasdfa',
        'supplierContact': '2342423423',
        'supplierBankDetails': 'asdf',
        'supplierCustomAttrib1': 'asfasdfasfa',
        'supplierCustomAttrib2': 'true',
        'supplierCustomAttrib3': '0%',
        'supplierCustomAttrib4': 'yes',
        'supplierCustomAttrib5': 'asdfasdf',
        'createdBy': null,
        'createdDate': '05-12-2018 10:42:07',
        'modifyBy': null,
        'modifyDate': null
      },
      {
        'id': 23,
        'supplierName': 'asdfasdf',
        'supplierAddress': 'asdfsdfasdfasdf',
        'supplierReference': 'asdfasdfasfasdfa',
        'supplierContact': '2342423423',
        'supplierBankDetails': 'asdf',
        'supplierCustomAttrib1': 'asfasdfasfa',
        'supplierCustomAttrib2': 'true',
        'supplierCustomAttrib3': '0%',
        'supplierCustomAttrib4': 'yes',
        'supplierCustomAttrib5': 'asdfasdf',
        'createdBy': null,
        'createdDate': '05-12-2018 10:42:07',
        'modifyBy': null,
        'modifyDate': null
      }, {
      'id': 24,
      'supplierName': 'asdfasdf',
      'supplierAddress': 'asdfsdfasdfasdf',
      'supplierReference': 'asdfasdfasfasdfa',
      'supplierContact': '2342423423',
      'supplierBankDetails': 'asdfasdfasdf',
      'supplierCustomAttrib1': 'asfasdfasfa',
      'supplierCustomAttrib2': 'true',
      'supplierCustomAttrib3': '0%',
      'supplierCustomAttrib4': 'yes',
      'supplierCustomAttrib5': 'asdfasdf',
      'createdBy': null,
      'createdDate': '05-12-2018 10:42:08',
      'modifyBy': null,
      'modifyDate': null
    }, {
      'id': 25,
      'supplierName': 'asdfasdf',
      'supplierAddress': 'asdfsdfasdfasdf',
      'supplierReference': 'asdfasdfasfasdfa',
      'supplierContact': '2342423423',
      'supplierBankDetails': 'asdfasdfasdf',
      'supplierCustomAttrib1': 'asfasdfasfa',
      'supplierCustomAttrib2': 'true',
      'supplierCustomAttrib3': '10%',
      'supplierCustomAttrib4': 'yes',
      'supplierCustomAttrib5': 'asdfasdf',
      'createdBy': null,
      'createdDate': '05-12-2018 10:42:10',
      'modifyBy': null,
      'modifyDate': null
    }, {
      'id': 26,
      'supplierName': 'asdfasdf',
      'supplierAddress': 'asdfsdfasdfasdf',
      'supplierReference': 'asdfasdfasfasdfa',
      'supplierContact': '2342423423',
      'supplierBankDetails': 'asdfasdfasdf',
      'supplierCustomAttrib1': 'asfasdfasfa',
      'supplierCustomAttrib2': 'true',
      'supplierCustomAttrib3': '10%',
      'supplierCustomAttrib4': 'yes',
      'supplierCustomAttrib5': 'asdfasdf',
      'createdBy': null,
      'createdDate': '05-12-2018 10:42:10',
      'modifyBy': null,
      'modifyDate': null
    }, {
      'id': 27,
      'supplierName': 'asdfasdf',
      'supplierAddress': 'asdfsdfasdfasdf',
      'supplierReference': 'asdfasdfasfasdfa',
      'supplierContact': '2342423423',
      'supplierBankDetails': 'asdfasdfasdf',
      'supplierCustomAttrib1': 'asfasdfasfa',
      'supplierCustomAttrib2': 'true',
      'supplierCustomAttrib3': '10%',
      'supplierCustomAttrib4': 'yes',
      'supplierCustomAttrib5': 'asdfasdf',
      'createdBy': null,
      'createdDate': '05-12-2018 10:42:10',
      'modifyBy': null,
      'modifyDate': null
    }, {
      'id': 28,
      'supplierName': 'asdfasdf',
      'supplierAddress': 'asdfsdfasdfasdfasdf',
      'supplierReference': 'asdfasdfasfasdfa',
      'supplierContact': '2342423423',
      'supplierBankDetails': 'asdfasdfasdfasdf',
      'supplierCustomAttrib1': 'asfasdfasfaasdfasdfasdf',
      'supplierCustomAttrib2': 'true',
      'supplierCustomAttrib3': '10%',
      'supplierCustomAttrib4': 'yes',
      'supplierCustomAttrib5': 'asdfasdf',
      'createdBy': null,
      'createdDate': '05-12-2018 10:42:14',
      'modifyBy': null,
      'modifyDate': null
    }, {
      'id': 29,
      'supplierName': 'asdfasdf',
      'supplierAddress': 'asdfsdfasdfasdfasdf',
      'supplierReference': 'asdfasdfasfasdfa',
      'supplierContact': '2342423423',
      'supplierBankDetails': 'asdfasdfasdfasdf',
      'supplierCustomAttrib1': 'asfasdfasfaasdfasdfasdf',
      'supplierCustomAttrib2': 'true',
      'supplierCustomAttrib3': '10%',
      'supplierCustomAttrib4': 'yes',
      'supplierCustomAttrib5': 'asdfasdf',
      'createdBy': null,
      'createdDate': '05-12-2018 10:42:14',
      'modifyBy': null,
      'modifyDate': null
    }, {
      'id': 30,
      'supplierName': 'asdfasdf',
      'supplierAddress': 'asdfsdfasdfasdfasdf',
      'supplierReference': 'asdfasdfasfasdfa',
      'supplierContact': '2342423423',
      'supplierBankDetails': 'asdfasdfasdfasdf',
      'supplierCustomAttrib1': 'asfasdfasfaasdfasdfasdf',
      'supplierCustomAttrib2': 'true',
      'supplierCustomAttrib3': '10%',
      'supplierCustomAttrib4': 'yes',
      'supplierCustomAttrib5': 'asdfasdf',
      'createdBy': null,
      'createdDate': '05-12-2018 10:42:14',
      'modifyBy': null,
      'modifyDate': null
    }, {
      'id': 31,
      'supplierName': 'asdfasdf',
      'supplierAddress': 'asdfsdfasdfasdfasdf',
      'supplierReference': 'asdfasdfasfasdfa',
      'supplierContact': '2342423423',
      'supplierBankDetails': 'asdfasdfasdfasdf',
      'supplierCustomAttrib1': 'asfasdfasfaasdfasdfasdf',
      'supplierCustomAttrib2': 'true',
      'supplierCustomAttrib3': '10%',
      'supplierCustomAttrib4': 'yes',
      'supplierCustomAttrib5': 'asdfasdf',
      'createdBy': null,
      'createdDate': '05-12-2018 10:42:14',
      'modifyBy': null,
      'modifyDate': null
    }, {
      'id': 32,
      'supplierName': 'asdfasdf',
      'supplierAddress': 'asdfsdfasdfasdfasdf',
      'supplierReference': 'asdfasdfasfasdfa',
      'supplierContact': '2342423423',
      'supplierBankDetails': 'asdfasdfasdfasdf',
      'supplierCustomAttrib1': 'asfasdfasfaasdfasdfasdf',
      'supplierCustomAttrib2': 'true',
      'supplierCustomAttrib3': '20%',
      'supplierCustomAttrib4': 'yes',
      'supplierCustomAttrib5': 'asdfasdf',
      'createdBy': null,
      'createdDate': '05-12-2018 10:42:16',
      'modifyBy': null,
      'modifyDate': null
    }, {
      'id': 33,
      'supplierName': 'asdfasdf',
      'supplierAddress': 'asdfsdfasdfasdfasdf',
      'supplierReference': 'asdfasdfasfasdfa',
      'supplierContact': '2342423423',
      'supplierBankDetails': 'asdfasdfasdfasdf',
      'supplierCustomAttrib1': 'asfasdfasfaasdfasdfasdf',
      'supplierCustomAttrib2': 'true',
      'supplierCustomAttrib3': '20%',
      'supplierCustomAttrib4': 'yes',
      'supplierCustomAttrib5': 'asdfasdf',
      'createdBy': null,
      'createdDate': '05-12-2018 10:42:16',
      'modifyBy': null,
      'modifyDate': null
    }, {
      'id': 34,
      'supplierName': 'asdfasdf',
      'supplierAddress': 'asdfsdfasdfasdfasdf',
      'supplierReference': 'asdfasdfasfasdfa',
      'supplierContact': '2342423423',
      'supplierBankDetails': 'asdfasdfasdfasdf',
      'supplierCustomAttrib1': 'asfasdfasfaasdfasdfasdf',
      'supplierCustomAttrib2': 'true',
      'supplierCustomAttrib3': '20%',
      'supplierCustomAttrib4': 'yes',
      'supplierCustomAttrib5': 'asdfasdf',
      'createdBy': null,
      'createdDate': '05-12-2018 10:42:16',
      'modifyBy': null,
      'modifyDate': null
    }, {
      'id': 35,
      'supplierName': 'asdfasdf',
      'supplierAddress': 'asdfsdfasdfasdfasdf',
      'supplierReference': 'asdfasdfasfasdfa',
      'supplierContact': '2342423423',
      'supplierBankDetails': 'asdfasdfasdfasdf',
      'supplierCustomAttrib1': 'asfasdfasfaasdfasdfasdf',
      'supplierCustomAttrib2': 'true',
      'supplierCustomAttrib3': '20%',
      'supplierCustomAttrib4': 'no',
      'supplierCustomAttrib5': 'asdfasdf',
      'createdBy': null,
      'createdDate': '05-12-2018 10:42:19',
      'modifyBy': null,
      'modifyDate': null
    }, {
      'id': 36,
      'supplierName': 'asdfasdf',
      'supplierAddress': 'asdfsdfasdfasdfasdf',
      'supplierReference': 'asdfasdfasfasdfa',
      'supplierContact': '2342423423',
      'supplierBankDetails': 'asdfasdfasdfasdf',
      'supplierCustomAttrib1': 'asfasdfasfaasdfasdfasdf',
      'supplierCustomAttrib2': 'true',
      'supplierCustomAttrib3': '20%',
      'supplierCustomAttrib4': 'no',
      'supplierCustomAttrib5': 'asdfasdf',
      'createdBy': null,
      'createdDate': '05-12-2018 10:42:19',
      'modifyBy': null,
      'modifyDate': null
    }, {
      'id': 37,
      'supplierName': 'asdfasdf',
      'supplierAddress': 'sdfasdfaasdfsdfasdfasdfasdf',
      'supplierReference': 'asdfasdfasfasdfa',
      'supplierContact': '2342423423',
      'supplierBankDetails': 'asdfasdfasdfasdf',
      'supplierCustomAttrib1': 'asfasdfasfaasdfasdfasdf',
      'supplierCustomAttrib2': 'true',
      'supplierCustomAttrib3': '20%',
      'supplierCustomAttrib4': 'no',
      'supplierCustomAttrib5': 'asdfasdf',
      'createdBy': null,
      'createdDate': '05-12-2018 10:42:22',
      'modifyBy': null,
      'modifyDate': null
    }, {
      'id': 38,
      'supplierName': 'asdfasdf',
      'supplierAddress': 'asdfasdf',
      'supplierReference': 'asdfasdfasfasdfa',
      'supplierContact': '2342423423',
      'supplierBankDetails': 'asdfasdfasdfasdf',
      'supplierCustomAttrib1': 'asfasdfasfaasdfasdfasdf',
      'supplierCustomAttrib2': 'true',
      'supplierCustomAttrib3': '20%',
      'supplierCustomAttrib4': 'no',
      'supplierCustomAttrib5': 'asdfasdf',
      'createdBy': null,
      'createdDate': '05-12-2018 10:42:23',
      'modifyBy': null,
      'modifyDate': null
    }, {
      'id': 39,
      'supplierName': 'asdfasdf',
      'supplierAddress': 'asdfasdfasdf',
      'supplierReference': 'asdfasdfasfasdfa',
      'supplierContact': '2342423423',
      'supplierBankDetails': 'asdfasdfasdfasdf',
      'supplierCustomAttrib1': 'asfasdfasfaasdfasdfasdf',
      'supplierCustomAttrib2': 'true',
      'supplierCustomAttrib3': '20%',
      'supplierCustomAttrib4': 'no',
      'supplierCustomAttrib5': 'asdfasdf',
      'createdBy': null,
      'createdDate': '05-12-2018 10:42:26',
      'modifyBy': null,
      'modifyDate': null
    }, {
      'id': 40,
      'supplierName': 'asdfasdf',
      'supplierAddress': 'asdfasdfsadfasf',
      'supplierReference': 'asdfasdfasfasdfa',
      'supplierContact': '2342423423',
      'supplierBankDetails': 'asdfasdfasdfasdf',
      'supplierCustomAttrib1': 'asfasdfasfaasdfasdfasdf',
      'supplierCustomAttrib2': 'true',
      'supplierCustomAttrib3': '20%',
      'supplierCustomAttrib4': 'no',
      'supplierCustomAttrib5': 'asdfasdf',
      'createdBy': null,
      'createdDate': '05-12-2018 10:42:28',
      'modifyBy': null,
      'modifyDate': null
    }, {
      'id': 41,
      'supplierName': 'asdfasdf',
      'supplierAddress': 'asdfasdfsadfasf',
      'supplierReference': 'asdfasdfasfasdfa',
      'supplierContact': '2342423423',
      'supplierBankDetails': 'asdfasdfasdfasdf',
      'supplierCustomAttrib1': 'asfasdfasfaasdfasdfasdf',
      'supplierCustomAttrib2': 'true',
      'supplierCustomAttrib3': '20%',
      'supplierCustomAttrib4': 'no',
      'supplierCustomAttrib5': 'asdfasdf',
      'createdBy': null,
      'createdDate': '05-12-2018 10:42:28',
      'modifyBy': null,
      'modifyDate': null
    }, {
      'id': 42,
      'supplierName': 'asdfasdf',
      'supplierAddress': 'asdfasdfsadfasf',
      'supplierReference': 'asdfasdfasfasdfa',
      'supplierContact': '2342423423',
      'supplierBankDetails': 'asdfasdfasdfasdf',
      'supplierCustomAttrib1': 'asfasdfasfaasdfasdfasdf',
      'supplierCustomAttrib2': 'true',
      'supplierCustomAttrib3': '20%',
      'supplierCustomAttrib4': 'no',
      'supplierCustomAttrib5': 'asdfasdf',
      'createdBy': null,
      'createdDate': '05-12-2018 10:42:28',
      'modifyBy': null,
      'modifyDate': null
    }, {
      'id': 43,
      'supplierName': 'asdfasdf',
      'supplierAddress': 'asdfasdfasdfasdfasdfsadfasf',
      'supplierReference': 'asdfasdfasfasdfa',
      'supplierContact': '2342423423',
      'supplierBankDetails': 'asdfasdfasdfasdf',
      'supplierCustomAttrib1': 'asfasdfasfaasdfasdfasdf',
      'supplierCustomAttrib2': 'true',
      'supplierCustomAttrib3': '20%',
      'supplierCustomAttrib4': 'no',
      'supplierCustomAttrib5': 'asdfasdf',
      'createdBy': null,
      'createdDate': '05-12-2018 10:42:30',
      'modifyBy': null,
      'modifyDate': null
    }, {
      'id': 44,
      'supplierName': 'asdfasdf',
      'supplierAddress': 'asdfasdfasdfasdfasdfsadfasf',
      'supplierReference': 'asdfasdfasfasdfa',
      'supplierContact': '2342423423',
      'supplierBankDetails': 'asdfasdfasdfasdf',
      'supplierCustomAttrib1': 'asfasdfasfaasdfasdfasdf',
      'supplierCustomAttrib2': 'true',
      'supplierCustomAttrib3': '20%',
      'supplierCustomAttrib4': 'yes',
      'supplierCustomAttrib5': 'asdfasdf',
      'createdBy': null,
      'createdDate': '05-12-2018 14:32:01',
      'modifyBy': null,
      'modifyDate': null
    }, {
      'id': 45,
      'supplierName': 'sdfasd',
      'supplierAddress': 'asdf',
      'supplierReference': 'fasdfasdf',
      'supplierContact': '3453453453',
      'supplierBankDetails': 'asdfa',
      'supplierCustomAttrib1': 'dfasdfasdf',
      'supplierCustomAttrib2': null,
      'supplierCustomAttrib3': '10%',
      'supplierCustomAttrib4': 'no',
      'supplierCustomAttrib5': 'asdfa',
      'createdBy': null,
      'createdDate': '05-12-2018 14:03:51',
      'modifyBy': null,
      'modifyDate': null
    }, {
      'id': 46,
      'supplierName': null,
      'supplierAddress': null,
      'supplierReference': null,
      'supplierContact': null,
      'supplierBankDetails': null,
      'supplierCustomAttrib1': null,
      'supplierCustomAttrib2': null,
      'supplierCustomAttrib3': null,
      'supplierCustomAttrib4': null,
      'supplierCustomAttrib5': null,
      'createdBy': null,
      'createdDate': '05-12-2018 15:54:40',
      'modifyBy': null,
      'modifyDate': null
    }, {
      'id': 47,
      'supplierName': null,
      'supplierAddress': null,
      'supplierReference': null,
      'supplierContact': null,
      'supplierBankDetails': null,
      'supplierCustomAttrib1': null,
      'supplierCustomAttrib2': null,
      'supplierCustomAttrib3': null,
      'supplierCustomAttrib4': null,
      'supplierCustomAttrib5': null,
      'createdBy': null,
      'createdDate': '05-12-2018 15:55:45',
      'modifyBy': null,
      'modifyDate': null
    }, {
      'id': 48,
      'supplierName': null,
      'supplierAddress': null,
      'supplierReference': null,
      'supplierContact': null,
      'supplierBankDetails': null,
      'supplierCustomAttrib1': null,
      'supplierCustomAttrib2': null,
      'supplierCustomAttrib3': null,
      'supplierCustomAttrib4': null,
      'supplierCustomAttrib5': null,
      'createdBy': null,
      'createdDate': '05-12-2018 15:56:05',
      'modifyBy': null,
      'modifyDate': null
    }, {
      'id': 50,
      'supplierName': 'asdfasdf',
      'supplierAddress': 'sadfasd',
      'supplierReference': 'true',
      'supplierContact': 'fasdf',
      'supplierBankDetails': 'asdfasdf',
      'supplierCustomAttrib1': null,
      'supplierCustomAttrib2': null,
      'supplierCustomAttrib3': null,
      'supplierCustomAttrib4': null,
      'supplierCustomAttrib5': null,
      'createdBy': null,
      'createdDate': '06-12-2018 17:40:47',
      'modifyBy': null,
      'modifyDate': null
    }];

}
